### ISSUE TITLE
[Feature] 가입-약관동의 화면 기능 구현

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/baemin-10#14]
## 요구사항
1. 필수 항목이 모두 선택되면 하단 ‘다음으로' 버튼이 활성화 된다.
전체 동의를 누르면 모두 선택된다.  다시 누르면 모두 해제된다.

2. 두 개 중 하나를 선택할 수 있다.

3. 다음으로 버튼을 누르면 다음페이지가 노출된다.

(선택) 약관 종류를 서버에서 관리할 수 있다.

## 개발방법
* 체크박스 input으로 상태 관리
* radio박스 input으로 상태 관리

## 다른 접근 방법
* 자바스크립트로 상태 관리

## 주의할 점
* 모두 동의 안되었을 때 버튼 활성화 예외 상황 처리
* 선택사항이 체크되지 않아도 버튼 활성화
* 나이 선택 두개 동시에 선택되지 않도록

**Comment by peanut-lover** [comment]
상태는 따로 자바스크립트 변수로 관리하지않고 Form 안 Input DOM Element만으로 관리하는게 구현이 더 가볍기 때문에 그렇게 진행했습니다.
