### ISSUE TITLE
[Bug] Main 화면 Markup 모바일 화면에 세로방향이 확장되지않습니다.

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/baemin-10#28]
## 버그

정확한 원인을 찾아내서 마크업 리뷰가 필요합니다. @edegiil 

<img width="380" alt="스크린샷 2021-07-07 오전 10 14 13" src="https://user-images.githubusercontent.com/20085849/124685359-17648f80-df0c-11eb-8f15-e50511e32c6d.png">

**Comment by edegiil** [comment]
해결완료!
