### ISSUE TITLE
[Wiki] 사용된 텍스트 검증을 위한 Regex 문서화해두기

### ISSUE THREAD

**Issue by peanut-lover** [woowa-techcamp-2021/baemin-10#40]
## 내용

회원가입 절차에 사용된 regex 들을 정리하기 위한 문서화가 필요해보입니다.

해당 이슈처리는 우선순위가 가장 낮으니 프로젝트 정리시 진행해봅시다.

**Comment by edegiil** [comment]
위키에 정리했습니다.

[위키 정규표현식 정리](https://github.com/woowa-techcamp-2021/baemin-10/wiki/%EC%9D%B4%EB%B2%88-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%EB%90%9C-%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D)

**Comment by peanut-lover** [comment]
패스워드 정규식에서 조금 의문이 있어서 남깁니다.

각 조합을 나타낼때 `.*[a-z]` 이런식으로 `.`를 붙이시던데 없어도 되지않나요?
